# Generated by Django 3.1.7 on 2021-04-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210412_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='msg',
            new_name='desc',
        ),
    ]
